language: python
python:
  - "2.7"
# command to install dependencies

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-scikit-learn

install:
  - pip install coveralls
  - pip install scikit-learn
  - pip install .

script: nosetests

after_success:
  coveralls
