language: python

python:
  - "2.7"
  - "3.5"
# command to install dependencies

before_install:
  - sudo apt-get update
  - sudo apt-get install gcc
  - sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran

install:
  - travis_wait pip install -I numpy==1.9.3 # https://github.com/numpy/numpy/issues/6462
  - travis_wait pip install scipy
  - travis_wait pip install scikit-learn
  - travis_wait pip install pandas
  - pip install .
  - cd mzos/third_party/emass && make
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=mzos

after_success:
  - coveralls
