language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install coveralls
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install .

script: nosetests --with-coverage --cover-package=mzos

after_success:
  coveralls
