language: python
python:
  - "2.7"
# command to install dependencies

virtualenv:
  - "2.7_with_system_site_packages"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-sklearn

install:
  - pip install coveralls
  - pip install .

script: nosetests --with-coverage --cover-package=mzos

after_success:
  coveralls --config-file .coveragerc
