sudo: false
language: python

python:
  - "2.7_with_system_site_packages"
# command to install dependencies

before_install:
  - sudo apt-get update
  - sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran
  #- sudo apt-get install python-numpy python-scipy python-sklearn

install:
  - pip install -I numpy==1.9.3
  - pip install scipy
  - pip install scikit-learn
  - pip install .
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=mzos

after_success:
  - coveralls
