language: python
python:
  - "2.7"
# command to install dependencies

install:
  - sudo apt-get install -qq python-numpy python-scipy python-sklearn
  - pip install coveralls
  - pip install . #- pip install scikit-learn

script: nosetests

after_success:
  coveralls
